name: Deploy to Railway

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    # This line runs the job inside a container with the Railway CLI
    container: ghcr.io/railwayapp/cli:latest
    
    env:
      # This makes the secret available to the whole job
      RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Railway
        # This command is now available because of the container
        run: railway up
