name: Deploy to Railway

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    # This line is the main fix. It runs the entire job inside
    # a container that already has the Railway CLI installed.
    container: ghcr.io/railwayapp/cli:latest
    
    # Environment variables are now at the job level
    env:
      RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
      
    steps:
      # Step 1: Check out your repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Run the Railway deployment command
      # The 'railway' command is available because we are in the container
      - name: Deploy to Railway
        run: railway up
